### ISSUE TITLE
raise exception asap is no device detected by udid in stf

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#115]
for the wireless devices we registered by ip address but in stf it was ip:5555.
as result session request stuck in a queue and was cancelled by timeout only.

in case of such mismatch we have to raise exception asap and crash the session. just returning false is not enough because in this case we don't pay attention to the configuration mismatch

**Comment by vdelendik** [comment]
@akamarouski, please restest. it seems like with latest changes it should fail correctly asap without timeout.
Also, make sure to test with true/false values for `GRID_THROW_ON_CAPABILITY_NOT_PRESENT` var

**Comment by akamarouski** [comment]
Added checking is there device with such udid to the moment when we create node in grid. If there are no such device, we will raise `GridException`

For testing let's try to change device serial in RethinkDB

**Comment by akamarouski** [comment]
could not open RethingDB using UI

**Comment by dhreben** [comment]
Will be tested on production
