### ISSUE TITLE
add devicename and udid for log messages related to stf api calls

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#123]
we have to find a way to provide more details about exact device we wanna to use via grid+stf 
```
17:28:59.975 INFO [STFClient.reserveDevice] - already reserved manually by the same user
...
17:30:14.574 INFO [MobileRemoteProxy.afterSession] - Session [] will be closed.

```

**Comment by akamarouski** [comment]
Added unique id like `[NODE-<uuid>]` and `[STF-<uuid>]` that contains unique uuid for each session, so we can filter logs and find all necessary logic like id of the device, name and so on

**Comment by akamarouski** [comment]
Could be tested with the `mcloud-grid:2.4-beta6`

**Comment by dhreben** [comment]
Verified.
