### ISSUE TITLE
investigate the better place for status-wda and status-adb verification

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#126]
it seems like as of now we do device reservationin stf and after that do wda/adb verification call.
is it possible to do before reservation especially if appium url is available on before session

**Comment by akamarouski** [comment]
`status-adb` and `status-wda` checks moved -  before device reservation in STF
Could be tested with the `mcloud-grid:2.4-beta6`

**Comment by dhreben** [comment]
Verified.
