### ISSUE TITLE
improve integration with stf

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#14]
integration with STF should be automatically enabled if 
1. STF_URL and STF_TOKEN not null
2. Connection to STF established during startup.

Also we have to provide possibility to override integration using custom capability:
enableStf=true.

If connection is not established using non empty stf url/token we shouldn't proceed with services startup and kill everything

**Comment by vdelendik** [comment]
done. changes are ported into the zebrunner branch: develop

**Comment by dhreben** [comment]
Verified.
