### ISSUE TITLE
Change default timeouts

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/mcloud-grid#145]
Remove `GRID_MAX_SESSION` from env variables and set as 1 in configuration.
Change `GRID_NEW_SESSION_WAIT_TIMEOUT` from 240000 to 600000 milliseconds (10 min)
Change `GRID_BROWSER_TIMEOUT` from 30000 to 0
Change `GRID_TIMEOUT` from 30000 to 150  seconds

**Comment by dhreben** [comment]
Verified on prod
