### ISSUE TITLE
Refactor new session logic with STF interaction

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/mcloud-grid#147]
Cache node options (udid, deviceName and so on).
Move appium check initialization to the constructor.
Remove custom lock.
Move appium check call, STF reservation and so on after `getNewSession` super call.
Remove STF object creation and reuse only static methods.
Always return device for `default` stf token.
Ignore device `30m` if we could not reserve it in STF with `0` status.

**Comment by dhreben** [comment]
Basic acceptance has been successfully completed
