### ISSUE TITLE
setup default ios and android video recording options

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#18]
declare default recording quality settings for iOS and android with ability to override via selenium capabilities.
https://github.com/zebrunner/mcloud-grid/blob/7d8bf9dc158c708f7d55b9323819d83f4aac499f/src/main/java/com/qaprosoft/carina/grid/MobileRemoteProxy.java#L224

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-grid/commit/3c3218020f5cc633155612cf5142e10e6130f912

during the testing make sure to run android and ios sample using `7.0.0-SNAPSHOT` carina. For both platforms video recordings should be available after tests execution

**Comment by vdelendik** [comment]
it was discovered that overriden video options not applied.
valid log from previous releases:
```
^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mPOST^[[39m ^[[37m/wd/hub/session/8d65d727-9c23-48c7-86ac-36f36a42ecbf/appium/start_recording_screen^[[39m
^[[35m[HTTP]^[[39m ^[[90m{"options":{"timeLimit":600,"videoType":"libx264","videoQuality":"medium","videoScale":"-2:720","videoFps":10}}^[[39m
^[[35m[W3C (8d65d727)]^[[39m Calling AppiumDriver.startRecordingScreen() with args: [{"timeLimit":600,"videoType":"libx264","videoQuality":"medium","videoScale":"-2:720","videoFps":10},"8d65d
```

current logs
```
^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mPOST^[[39m ^[[37m/wd/hub/session/f8ed932c-cb8a-49b8-ab9d-39a74fb5a245/appium/start_recording_screen^[[39m
^[[35m[HTTP]^[[39m ^[[90m{"options.videoType":"libx264","options.videoQuality":"medium","options.videoScale":"-2:720","options.videoFps":"10"}^[[39m
^[[35m[W3C (f8ed932c)]^[[39m Calling AppiumDriver.startRecordingScreen() with args: [null,"f8ed932c-cb8a-49b8-ab9d-39a74fb5a245"]
```


need review options params setup again

**Comment by vdelendik** [comment]
Found valid way to override default video recrding settings. 
During testing we have to run android default mobile test. Confirmation that our settings applied video should start from this frame:
![image](https://user-images.githubusercontent.com/4551455/104814797-bd6af300-5821-11eb-9fee-cc25f2ae3753.png)

**Comment by dhreben** [comment]
Verified.
