### ISSUE TITLE
do user token verification for every STF client object

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#32]
For each new session request we generate new STFClient object to be able to override token and timeout.
For now disabled all kind of calls as previous get devices call has no sense at all.

Let's do instead getting user details by token to make sure:
1. we have valid token which can be authenticated
2. put into the log user name which is returned by token.

https://github.com/openstf/stf/blob/master/doc/API.md#user
curl -H "Authorization: Bearer YOUR-TOKEN-HERE" https://stf.example.org/api/v1/user

Example:
```
curl -H "Authorization: Bearer ..." https://demo...:443/api/v1/user
{"success":true,"user":{"adbKeys":[{"fingerprint":"...c:bc:33:85:58:67:98:86:65:39:32","title":"@unknown"}],"createdAt":"2021-01-29T09:55:35.636Z","email":"admin@gmail.com","forwards":[],"group":"EZrL8XTMTGq+0/7TbVe2hA==","groups":{"lock":false,"quotas":{"allocated":{"duration":1296000000,"number":5},"consumed":{"duration":0,"number":0},"defaultGroupsDuration":0,"defaultGroupsNumber":0,"defaultGroupsRepetitions":0,"repetitions":10},"subscribed":["89baa04560ee4adda72c31d3ed07d20e"]},"ip":"::ffff:172.18.0.21","lastLoggedInAt":"2021-02-04T16:02:00.017Z","name":"admin","privilege":"user","settings":{"dateFormat":"M/d/yy h:mm:ss a","deviceListActiveTabs":{"details":true,"icons":false},"emailAddressSeparator":",","lastUsedDevice":"..."}}}
```

**Comment by vdelendik** [comment]
To emulate invalid token you can provide any value via
```
capabilitites.STF_TOKEN=broken token
```

**Comment by dhreben** [comment]
Verified.
Open new ticket https://github.com/zebrunner/mcloud-grid/issues/40
