### ISSUE TITLE
verify that stf integration is valid without 4 min timeout

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#33]
in case someone provide invalid STF_TOKEN via capabilitites we are waiting default 4 min timeout before raising exception.
need find a way to verify token asap and return an exception to the client asap as well.

in v1.0 we overrided hasCapability which could verify it on the fly and return false, i.e. deactivate node asap.

```
    @Override
    public boolean hasCapability(Map<String, Object> requestedCapability) {
        // verify that require STF connection can be established trying to init STF client 
        try {
            getSTFClient(requestedCapability);
        } catch (Exception e) {
            // as we have enabled GRID_THROW_ON_CAPABILITY_NOT_PRESENT by default we could raise exception without waiting 4 minutes
            LOGGER.severe("Node '" + this + "' can't establish required STF connection!");
            return false;           
        }
        
        for (TestSlot slot : getTestSlots()) {
            if (slot.matches(requestedCapability)) {
                return true;
            }
        }

        return false;
    }
```

**Comment by vdelendik** [comment]
done. to test you have to setup CE of mcloud using develop branch and run any mobile job.
Make sure to provide as capabilities invalid value for `STF_TOKEN=invalid` to emulate any problem with STF.
-> as result each test should fail in a 60sec instead of 240 by default!
error message should be:
```
2022-01-23 16:30:59 Messager [TestNG-tests-1-26] [ERROR] TEST [Safari test - safariTest] FAILED at [16:30:59 2022-01-23] - org.openqa.selenium.WebDriverException: Error forwarding the new session Request timed out waiting for a node to become available.
Command duration or timeout: 60.91 seconds
```

**Comment by dhreben** [comment]
Verified.

![Screenshot 2022-01-24 at 17 04 51](https://user-images.githubusercontent.com/50950954/150797246-92dc1df6-dfc9-44db-9862-ccb9e1a15812.png)
