### ISSUE TITLE
[iOS] Video recording session is limited by 3 minutes timeout

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/mcloud-grid#38]
With the current implementation, we have 3 minutes timeout for iOS video recording

**Comment by vdelendik** [comment]
fixed in zebrunner/mcloud-grid:1.2-beta1 and higher

**Comment by vdelendik** [comment]
1800 is max time limit for appium video recording so build fresh image:
 zebrunner/mcloud-grid:1.2-beta2

**Comment by vdelendik** [comment]
confirmed from clients
