### ISSUE TITLE
STF containers shouldn't be recreated after create new mcloud-grid container

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-grid#42]
**Test scenario:**

1.cd zebrunner/mcloud
2.docker rm -f mcloud-grid
3../zebrunner.sh start

 **Actual result:** After deleting the mcloud-grid container and running it again, the stf containers are recreated together with mcloud-grid cointainer.

![Screen Shot 2021-04-30 at 4 33 13 PM](https://user-images.githubusercontent.com/50950954/116702499-d31bb700-a9d1-11eb-83ae-913bcc427115.png)

**Comment by vdelendik** [comment]
fixed indirectly... recreation might happen after updating shared variables.env and in this case docker recreate containers forcibly.
if nothing updating I see such behavior in upcoming mcloud 2.0
