### ISSUE TITLE
try to check usage ownership by token to allow automation launch over occupied devices

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#54]
1. let's assume device is free in selenium grid, i.e. nobody use it by automation
2. somebody wanna to debug something and occupied devices manually using his own personal stf token
3. we should allow to proceed with run in this case if we could determine that the same person occupied
Moreover it might fix pretty serious #10 ticket as well.

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-grid/pull/57

test scenarios should cover such steps:
1. deploy CE or mcloud using develop branch. Integrate STF using `admin` user token
2. run mobile tests when nobody occupy device
-> nothing new, device is occupied automatically by `admin` and return to available list per each test
3. occupy device by `admin` user manually and run tests
-> tests should be started using your `admin` session and you should see actual actions on device
4. occupy device under `non-admin` user and launch tests vs occupied device
-> tests should wait upto 4 min, request is in queue in `/mcloud/grid/console` hub ui. As only you stop using -> tests should occupy device and run
5. and finally, generate new STF access token for `non-admin` user, occupy device by `non-admin` user, run mobile tests vs occupied device but provide also via capabilities extra param: `STF_TOKEN=<token>`
-> tests should be executed via occupied device, you should see actual action as non-admin user

**Comment by dhreben** [comment]
Verified
