### ISSUE TITLE
deviceName capability is ignored using latest selenium/appium clients

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#82]
on selenium 4, appium 8.2.0 client requested deviceName capability is ignored and we run tests on any device.
it should be fixed after finishing #79

**Comment by vdelendik** [comment]
provided hotfix using selenium server v3.

to test we have to play with CE from develop version and capabilities:
```
deviceName=Nokia_3
deviceName=Nokia_3,HTC_Ultra

udid=udid1
udid=udid1, udid2
```
try also occupy device in STF during mobile sample demo job execution using different STF account (not the same which is used for integration)

**Comment by dhreben** [comment]
Verified on prod
