### ISSUE TITLE
no video recordings on selenium4/appium2

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#83]
seems like new capabilities with appium/zebrunner prefix coudn't be detected correctly. as result enableVideo is lost and no uploaded video... related ticket is  #79

**Comment by vdelendik** [comment]
fixed on reporting side. root cause new w3c caps and provider prefix: `appium:`

**Comment by dhreben** [comment]
Still repro on demo.zebrunner.farm
Screenshots are available,but video is absent

**Comment by vdelendik** [comment]
@dhreben, resolving as no issues on production detected. let's test first of all embedded S3 minio setup.
