### ISSUE TITLE
unable to return device artifacts to the carina

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-grid#91]
we used slotCapabilities node to return information about devices how they registered in device farm.
with latest appium2.0 and adjusted in #89 ncloud-grid this functionality is broken.

![image](https://github.com/zebrunner/mcloud-grid/assets/4551455/e7308111-433f-412b-afa8-df733fd4ea31)

let's review process and simplify as much as possible

**Comment by vdelendik** [comment]
fixed by adding prefix `zebrunner:` to requested slotCapabilities.
@dhreben, testing might be started when we finish movement to appium 2.0 and new carina is out which can handle this new prefixed param

after execution on device farm we have to assign device label as it is named in stf.

**Comment by dhreben** [comment]
Fixed

<img width="208" alt="Screenshot 2023-08-03 at 18 15 42" src="https://github.com/zebrunner/mcloud-grid/assets/50950954/24c851b9-2867-420a-81e6-69f3a925f2fe">
